### ISSUE TITLE
Error while adding components to dashboard object

### ISSUE THREAD

**Issue by ashishjain1988** [loosolab/i2dash#4]
Hi,

I am getting the following error while adding a component to the dashboard object after initialization.

Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '/Volumes/Temp/tmp/RtmpivoWUQ/obj_HGxp0z.rds', probable reason 'No such file or directory'

Also, I don't have a '/Volumes/Temp/' directory so I am not sure why it is looking for a temp file in that folder.

**Comment by jenzopr** [comment]
Hi and thanks for pointing out the issue!

Can you please provide the following information:

- How did you initialise the `i2dashboard` object?
- Which value have you set in the `$datadir` slot? (`i2dashboard$datadir`)
- What is the output of `file.path(tempdir())` on your system?

I assume that something went ugly during determining a valid tempdir to store additional information. We normally rely on R's `tempdir()` function, but you can overwrite that in the constructor of the i2dashboard:

```
library(i2dash)
obj <- i2dashboard(..., datadir = '/some/existing/path')
```

Best,
Jens

**Comment by ashishjain1988** [comment]
Hi Jens,

Thank you for the response. I just checked that I was not setting the datadir of the dashboard object (assuming it's going to store it in the current directory). After setting the "datadir", I am not getting the error. Also, when I checked the default datadir of the dashboard object it shows "/Volumes/Temp/tmp/RtmpivoWUQ".

Thanks,
Ashish
